name: My First Workflow

on:
  push:
    branches:
     - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      loglevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
        

jobs:
  MyFirstJob:
    runs-on:  ubuntu-latest

    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
