name: My First Workflow

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run a Perl script
      - run: print %ENV
        shell: perl {0}
