name: Run a Perl shell

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  FirstPerlJob:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run a Perl script
        run: |
          use Data::Dumper;
          print "Hello World!\n";
          print '-' x 80 . "\n";
          print Data::Dumper->Dump([\%ENV], [qw(ENV)]);
        shell: perl {0}
