name: Run a Perl shell

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  FirstPerlJob:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run a Perl script
        run: |
          print "Hello World!";
          print '-' x 80 . "\n";
          print %ENV
        shell: perl {0}
