# This is a basic workflow to help you get started with Actions

name: MASTER Create Apache package

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value-1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test-self-hosted:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Show content of scratch
        run: |
          echo Hi, Juergen!
          echo We want to access to the local self-hosted machine....
          echo Current directory: `pwd`
          ls -al
          echo --------
          ls /home/scratch/keep/js
  
      - name: Show content of master
        run: |
          ls -al /home/master
  
      - name: Copy apache from master to scratch/keep/js/Linux
        run: |
          set -x
          mkdir -p /home/scratch/keep/js/Linux/TEMP/apache
            cp -TRv /home/master/apache_2.4.57 /home/scratch/keep/js/Linux/TEMP/apache
